openapi: 3.0.1
info:
  title: SimpleCRUDAPI
  description: API Definition of SimpleCRUDAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/simplecrud
paths:
  /:
    get:
      responses:
        default:
          description: Default response
